### ISSUE TITLE
Using Nuxt: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by chantelprows** [iliyaZelenko/tiptap-vuetify-nuxt#3]
getting error
Module parse failed: Unexpected token (4925:17)
You may need an appropriate loader to handle this file type.
|     render(h, context) {
|       const data = {
|         props: { ...context.props,
|           name
|         },
 whenever I try to build

**Comment by iliyaZelenko** [comment]
I was informed about the same error earlier https://github.com/iliyaZelenko/tiptap-vuetify/issues/106. I can’t understand exactly what this error is about.

I updated my [nuxt demo](https://codesandbox.io/s/github/iliyaZelenko/tiptap-vuetify-nuxt/tree/master/) to current package's version and everything works fine there.

A little google, I found [such a solution](https://github.com/webpack/webpack/issues/8656#issuecomment-456010969), it can help. 

I have an uncertain assumption that this may be due to [some builds of Vue](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds). Maybe you know what build you use?

I really want to help, but I don’t know what’s the problem.

**Comment by jggj21** [comment]
I get the same problem, how was it corrected?

**Comment by vedmant** [comment]
I also have "Unexpected token 'export'"

**Comment by imshadowz** [comment]
Hello, I got same problem and I solved by add this line to nuxt.config.js
```js
build: {
    transpile: ['vuetify/lib', "tiptap-vuetify"]
}
```

Hope it can help you too.

**Comment by 777genius** [comment]
> Hello, I got same problem and I solved by add this line to nuxt.config.js
> 
> ```js
> build: {
>     transpile: ['vuetify/lib', "tiptap-vuetify"]
> }
> ```
> 
> Hope it can help you too.

This is also indicated in the [description](https://github.com/iliyaZelenko/tiptap-vuetify-nuxt#transpile). Then I mark it as resolved.
